/*
 * MIT License

 * Copyright (c) 2016 Garrett Vargas

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


module.exports = {
    'Bulbasaur':{index:1, types:['Grass','Poison']},
    'Ivysaur':{index:2, types:['Grass','Poison']},
    'Venusaur':{index:3, types:['Grass','Poison']},
    'Charmander':{index:4, types:['Fire']},
    'Charmeleon':{index:5, types:['Fire']},
    'Charizard':{index:6, types:['Fire','Flying']},
    'Squirtle':{index:7, types:['Water']},
    'Wartortle':{index:8, types:['Water']},
    'Blastoise':{index:9, types:['Water']},
    'Caterpie':{index:10, types:['Bug']},
    'Metapod':{index:11, types:['Bug']},
    'Butterfree':{index:12, types:['Bug','Flying']},
    'Weedle':{index:13, types:['Bug','Poison']},
    'Kakuna':{index:14, types:['Bug','Poison']},
    'Beedrill':{index:15, types:['Bug','Poison']},
    'Pidgey':{index:16, types:['Normal','Flying']},
    'Pidgeotto':{index:17, types:['Normal','Flying']},
    'Pidgeot':{index:18, types:['Normal','Flying']},
    'Rattata':{index:19, types:['Normal']},
    'Raticate':{index:20, types:['Normal']},
    'Spearow':{index:21, types:['Normal','Flying']},
    'Fearow':{index:22, types:['Normal','Flying']},
    'Ekans':{index:23, types:['Poison']},
    'Arbok':{index:24, types:['Poison']},
    'Pikachu':{index:25, types:['Electric']},
    'Raichu':{index:26, types:['Electric']},
    'Sandshrew':{index:27, types:['Ground']},
    'Sandslash':{index:28, types:['Ground']},
    'Nidoran Female':{index:29, types:['Poison']},
    'Nidorina':{index:30, types:['Poison']},
    'Nidoqueen':{index:31, types:['Poison','Ground']},
    'Nidoran Male':{index:32, types:['Poison']},
    'Nidorino':{index:33, types:['Poison']},
    'Nidoking':{index:34, types:['Poison','Ground']},
    'Clefairy':{index:35, types:['Fairy']},
    'Clefable':{index:36, types:['Fairy']},
    'Vulpix':{index:37, types:['Fire']},
    'Ninetales':{index:38, types:['Fire']},
    'Jigglypuff':{index:39, types:['Normal','Fairy']},
    'Wigglytuff':{index:40, types:['Normal','Fairy']},
    'Zubat':{index:41, types:['Poison','Flying']},
    'Golbat':{index:42, types:['Poison','Flying']},
    'Oddish':{index:43, types:['Grass','Poison']},
    'Gloom':{index:44, types:['Grass','Poison']},
    'Vileplume':{index:45, types:['Grass','Poison']},
    'Paras':{index:46, types:['Bug','Grass']},
    'Parasect':{index:47, types:['Bug','Grass']},
    'Venonat':{index:48, types:['Bug','Poison']},
    'Venomoth':{index:49, types:['Bug','Poison']},
    'Diglett':{index:50, types:['Ground']},
    'Dugtrio':{index:51, types:['Ground']},
    'Meowth':{index:52, types:['Normal']},
    'Persian':{index:53, types:['Normal']},
    'Psyduck':{index:54, types:['Water']},
    'Golduck':{index:55, types:['Water']},
    'Mankey':{index:56, types:['Fighting']},
    'Primeape':{index:57, types:['Fighting']},
    'Growlithe':{index:58, types:['Fire']},
    'Arcanine':{index:59, types:['Fire']},
    'Poliwag':{index:60, types:['Water']},
    'Poliwhirl':{index:61, types:['Water']},
    'Poliwrath':{index:62, types:['Water','Fighting']},
    'Abra':{index:63, types:['Psychic']},
    'Kadabra':{index:64, types:['Psychic']},
    'Alakazam':{index:65, types:['Psychic']},
    'Machop':{index:66, types:['Fighting']},
    'Machoke':{index:67, types:['Fighting']},
    'Machamp':{index:68, types:['Fighting']},
    'Bellsprout':{index:69, types:['Grass','Poison']},
    'Weepinbell':{index:70, types:['Grass','Poison']},
    'Victreebel':{index:71, types:['Grass','Poison']},
    'Tentacool':{index:72, types:['Water','Poison']},
    'Tentacruel':{index:73, types:['Water','Poison']},
    'Geodude':{index:74, types:['Rock','Ground']},
    'Graveler':{index:75, types:['Rock','Ground']},
    'Golem':{index:76, types:['Rock','Ground']},
    'Ponyta':{index:77, types:['Fire']},
    'Rapidash':{index:78, types:['Fire']},
    'Slowpoke':{index:79, types:['Water','Psychic']},
    'Slowbro':{index:80, types:['Water','Psychic']},
    'Magnemite':{index:81, types:['Electric','Steel']},
    'Magneton':{index:82, types:['Electric','Steel']},
    'Farfetched':{index:83, types:['Normal','Flying']},
    'Doduo':{index:84, types:['Normal','Flying']},
    'Dodrio':{index:85, types:['Normal','Flying']},
    'Seel':{index:86, types:['Water']},
    'Dewgong':{index:87, types:['Water','Ice']},
    'Grimer':{index:88, types:['Poison']},
    'Muk':{index:89, types:['Poison']},
    'Shellder':{index:90, types:['Water']},
    'Cloyster':{index:91, types:['Water','Ice']},
    'Gastly':{index:92, types:['Ghost','Poison']},
    'Haunter':{index:93, types:['Ghost','Poison']},
    'Gengar':{index:94, types:['Ghost','Poison']},
    'Onix':{index:95, types:['Rock','Ground']},
    'Drowzee':{index:96, types:['Psychic']},
    'Hypno':{index:97, types:['Psychic']},
    'Krabby':{index:98, types:['Water']},
    'Kingler':{index:99, types:['Water']},
    'Voltorb':{index:100, types:['Electric']},
    'Electrode':{index:101, types:['Electric']},
    'Exeggcute':{index:102, types:['Grass','Psychic']},
    'Exeggutor':{index:103, types:['Grass','Psychic']},
    'Cubone':{index:104, types:['Ground']},
    'Marowak':{index:105, types:['Ground']},
    'Hitmonlee':{index:106, types:['Fighting']},
    'Hitmonchan':{index:107, types:['Fighting']},
    'Lickitung':{index:108, types:['Normal']},
    'Koffing':{index:109, types:['Poison']},
    'Weezing':{index:110, types:['Poison']},
    'Rhyhorn':{index:111, types:['Ground','Rock']},
    'Rhydon':{index:112, types:['Ground','Rock']},
    'Chansey':{index:113, types:['Normal']},
    'Tangela':{index:114, types:['Grass']},
    'Kangaskhan':{index:115, types:['Normal']},
    'Horsea':{index:116, types:['Water']},
    'Seadra':{index:117, types:['Water']},
    'Goldeen':{index:118, types:['Water']},
    'Seaking':{index:119, types:['Water']},
    'Staryu':{index:120, types:['Water']},
    'Starmie':{index:121, types:['Water','Psychic']},
    'Mr. Mime':{index:122, types:['Psychic','Fairy']},
    'Scyther':{index:123, types:['Bug','Flying']},
    'Jynx':{index:124, types:['Ice','Psychic']},
    'Electabuzz':{index:125, types:['Electric']},
    'Magmar':{index:126, types:['Fire']},
    'Pinsir':{index:127, types:['Bug']},
    'Tauros':{index:128, types:['Normal']},
    'Magikarp':{index:129, types:['Water']},
    'Gyarados':{index:130, types:['Water','Flying']},
    'Lapras':{index:131, types:['Water','Ice']},
    'Ditto':{index:132, types:['Normal']},
    'Eevee':{index:133, types:['Normal']},
    'Vaporeon':{index:134, types:['Water']},
    'Jolteon':{index:135, types:['Electric']},
    'Flareon':{index:136, types:['Fire']},
    'Porygon':{index:137, types:['Normal']},
    'Omanyte':{index:138, types:['Rock','Water']},
    'Omastar':{index:139, types:['Rock','Water']},
    'Kabuto':{index:140, types:['Rock','Water']},
    'Kabutops':{index:141, types:['Rock','Water']},
    'Aerodactyl':{index:142, types:['Rock','Flying']},
    'Snorlax':{index:143, types:['Normal']},
    'Articuno':{index:144, types:['Ice','Flying']},
    'Zapdos':{index:145, types:['Electric','Flying']},
    'Moltres':{index:146, types:['Fire','Flying']},
    'Dratini':{index:147, types:['Dragon']},
    'Dragonair':{index:148, types:['Dragon']},
    'Dragonite':{index:149, types:['Dragon','Flying']},
    'Mewtwo':{index:150, types:['Psychic']},
    'Mew':{index:151, types:['Psychic']}
};
